# The list of all moving parts required to make 
# the loadbalancing work
# This is intentionaly not using Kubernetes native
# loadbalancing.

# Node server serving stuff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  labels:
    app: node-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        imagePullPolicy: IfNotPresent
        image: pkotas/node-server:latest
        ports:
          - containerPort: 8080
            name: server-port

# HAProxy loadbalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-server
  labels:
    app: proxy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-server
  template:
    metadata:
      labels:
        app: proxy-server
    spec:
      containers:
      - name: proxy-server
        imagePullPolicy: IfNotPresent
        image: pkotas/proxy-server:latest
        ports:
          - containerPort: 8080
            name: server-port

# Service definition needed to stitch it together
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: proxy-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: server-port
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: proxy-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: server-port
  type: NodePort
